In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Mrunmayee Joshi\Downloads\customer_shopping.csv")

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
(df['Discount Applied']==df['Promo Code Used']).all()

np.True_

In [8]:
df=df.drop('Discount Applied',axis=1)

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually

In [11]:
df.columns=df.columns.str.replace(' ','_')

In [12]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Promo_Code_Used', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='object')

In [14]:
df.columns=df.columns.str.replace('Purchase_Amount_(USD)','Purchase_Amount_USD')

In [15]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_USD', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Promo_Code_Used', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='object')

In [19]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
Item_Purchased            0
Category                  0
Purchase_Amount_USD       0
Location                  0
Size                      0
Color                     0
Season                    0
Review_Rating             0
Subscription_Status       0
Shipping_Type             0
Promo_Code_Used           0
Previous_Purchases        0
Payment_Method            0
Frequency_of_Purchases    0
dtype: int64

In [18]:
df['Review_Rating'] = df.groupby('Category')['Review_Rating'].transform(lambda x: x.fillna(x.median()))

In [22]:
label=['Young Adult','Adult','Middle','Old']
df['age_group'] = pd.qcut(df['Age'], q=4, labels=label)

In [27]:
frequency_mapping={
    'Fortnightly':14,
    'Bi-Weekly':14,
    'Weekly':7,
    'Monthly':30,
    'Every 3 months':30,
    'Quarterly':90,
    'Annually':350
     
}
df['Purchase_Frequency']=df['Frequency_of_Purchases'].map(frequency_mapping)

In [28]:
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_USD,Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases,age_group,Purchase_Frequency
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle,350.0

In [29]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 816.0 kB/s eta 0:00:22
   - -------------------------------------- 0.8/17.7 MB 994.4 kB/s eta 0:00:17
   -- ------------------------------------- 1.3/17.7 MB 1.4 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/17.7 MB 1.4 MB/s eta 0:00:12
   ---- ----------------------------------- 2.1/17.7 MB 1.5 MB/s eta 0:00:11
   ---- ----------------------------------- 2.1/17.7 MB 1.5 MB/s eta 0:00:11
   ----- ---------------------------------- 2.4/17.7 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.4/17.7 MB 1.3 MB/s eta 0:00:12
   ----- ---------------------------------- 2.6/17.7 MB 1.2 MB/s eta 0:00:13
   ------ --------------------------------- 2.9/17.7 MB 1.1 MB/s eta 0:00:14
   ------ --------------------------------- 2.9/17.7 MB 1.1 MB/s eta 0:00:14
   ------- -------------------------------- 3.1/17.7 MB 1.1 MB/s eta 0:00:14
   ------- -------------------------------- 3.1/17.7 MB 1.1 MB/s eta 0:00:14
   ------- -------------------------------- 3.4/17.7 MB 1.0 MB/s eta 0:00:14
   ------- -------------------------------- 3.4/17.7 MB 1.0 MB/s eta 0:00:14
   -------- ------------------------------- 3.7/17.7 MB 974.6 kB/s eta 0:00:15
   -------- ------------------------------- 3.9/17.7 MB 989.0 kB/s eta 0:00:14
   --------- ------------------------------ 4.2/17.7 MB 974.8 kB/s eta 0:00:14
   --------- ------------------------------ 4.2/17.7 MB 974.8 kB/s eta 0:00:14
   --------- ------------------------------ 4.2/17.7 MB 974.8 kB/s eta 0:00:14
   ---------- ----------------------------- 4.5/17.7 MB 895.4 kB/s eta 0:00:15
   ---------- ----------------------------- 4.5/17.7 MB 895.4 kB/s eta 0:00:15
   ---------- ----------------------------- 4.7/17.7 MB 892.8 kB/s eta 0:00:15
   ----------- ---------------------------- 5.0/17.7 MB 904.6 kB/s eta 0:00:15
   ----------- ---------------------------- 5.2/17.7 MB 916.7 kB/s eta 0:00:14
   ------------ --------------------------- 5.5/17.7 MB 926.1 kB/s eta 0:00:14
   ------------- -------------------------- 5.8/17.7 MB 923.6 kB/s eta 0:00:13
   ------------- -------------------------- 6.0/17.7 MB 949.6 kB/s eta 0:00:13
   -------------- ------------------------- 6.3/17.7 MB 958.9 kB/s eta 0:00:12
   -------------- ------------------------- 6.6/17.7 MB 955.8 kB/s eta 0:00:12
   --------------- ------------------------ 6.8/17.7 MB 950.0 kB/s eta 0:00:12
   ---------------- ----------------------- 7.1/17.7 MB 959.7 kB/s eta 0:00:12
   ---------------- ----------------------- 7.1/17.7 MB 959.7 kB/s eta 0:00:12
   ---------------- ----------------------- 7.3/17.7 MB 953.3 kB/s eta 0:00:11
   ---------------- ----------------------- 7.3/17.7 MB 953.3 kB/s eta 0:00:11
   ----------------- ---------------------- 7.6/17.7 MB 922.8 kB/s eta 0:00:11
   ----------------- ---------------------- 7.6/17.7 MB 922.8 kB/s eta 0:00:11
   ----------------- ---------------------- 7.9/17.7 MB 918.3 kB/s eta 0:00:11
   ------------------ --------------------- 8.1/17.7 MB 914.3 kB/s eta 0:00:11
   ------------------ --------------------- 8.4/17.7 MB 920.3 kB/s eta 0:00:11
   ------------------ --------------------- 8.4/17.7 MB 920.3 kB/s eta 0:00:11
   ------------------ --------------------- 8.4/17.7 MB 920.3 kB/s eta 0:00:11
   ------------------- -------------------- 8.7/17.7 MB 896.1 kB/s eta 0:00:11
   ------------------- -------------------- 8.7/17.7 MB 896.1 kB/s eta 0:00:11
   -------------------- ------------------- 8.9/17.7 MB 887.3 kB/s eta 0:00:10
   -------------------- ------------------- 8.9/17.7 MB 887.3 kB/s eta 0:00:10
   -------------------- ------------------- 9.2/17.7 MB 877.0 kB/s eta 0:00:10
   --------------------- ------------------ 9.4/17.7 MB 874.7 kB/s eta 0:00:10
   --------------------- ------------------ 9.4/17.7 MB 874.7 kB/s eta 0:00:10
   --------------------- ------------------ 9.7/17.7 MB 874.0 kB/s eta 0:00:10
   ---------------------- ----------------- 10.0/17.7 MB 873.3 kB/s eta 0:00:09
   ----------------------- ---------------- 10.2/17.7 MB 888.0 kB/s eta 0:00:09
   ----------------------- ---------------- 10.5/17.7 MB 894.5 kB/s eta 0:00:09
   ------------------------ --------------- 10.7/17.7 MB 901.0 kB/s eta 0:00:08
   ------------------------ --------------- 11.0/17.7 MB 897.9 kB/s eta 0:00:08
   ------------------------- -------------- 11.3/17.7 MB 904.3 kB/s eta 0:00:08
   -------------------------- ------------- 11.5/17.7 MB 910.1 kB/s eta 0:00:07
   -------------------------- ------------- 11.8/17.7 MB 921.8 kB/s eta 0:00:07
   --------------------------- ------------ 12.3/17.7 MB 933.1 kB/s eta 0:00:06
   ---------------------------- ----------- 12.6/17.7 MB 938.1 kB/s eta 0:00:06
   ----------------------------- ---------- 12.8/17.7 MB 950.4 kB/s eta 0:00:06
   ----------------------------- ---------- 13.1/17.7 MB 955.9 kB/s eta 0:00:05
   ----------------------------- ---------- 13.1/17.7 MB 955.9 kB/s eta 0:00:05
   ------------------------------ --------- 13.4/17.7 MB 946.2 kB/s eta 0:00:05
   ------------------------------ --------- 13.6/17.7 MB 949.0 kB/s eta 0:00:05
   ------------------------------- -------- 13.9/17.7 MB 953.6 kB/s eta 0:00:04
   ------------------------------- -------- 13.9/17.7 MB 953.6 kB/s eta 0:00:04
   -------------------------------- ------- 14.2/17.7 MB 943.2 kB/s eta 0:00:04
   -------------------------------- ------- 14.2/17.7 MB 943.2 kB/s eta 0:00:04
   -------------------------------- ------- 14.4/17.7 MB 933.6 kB/s eta 0:00:04
   --------------------------------- ------ 14.7/17.7 MB 931.0 kB/s eta 0:00:04
   --------------------------------- ------ 14.7/17.7 MB 931.0 kB/s eta 0:00:04
   --------------------------------- ------ 14.9/17.7 MB 923.3 kB/s eta 0:00:03
   ---------------------------------- ----- 15.2/17.7 MB 926.5 kB/s eta 0:00:03
   ---------------------------------- ----- 15.2/17.7 MB 926.5 kB/s eta 0:00:03
   ---------------------------------- ----- 15.5/17.7 MB 920.4 kB/s eta 0:00:03
   ----------------------------------- ---- 15.7/17.7 MB 924.5 kB/s eta 0:00:03
   ------------------------------------ --- 16.0/17.7 MB 928.2 kB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 928.2 kB/s eta 0:00:02
   ------------------------------------- -- 16.5/17.7 MB 936.4 kB/s eta 0:00:02
   ------------------------------------- -- 16.8/17.7 MB 940.5 kB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 943.9 kB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 943.9 kB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 941.1 kB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 939.4 kB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 939.2 kB/s  0:00:18
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [30]:
import mysql.connector

In [32]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Mrun@SQL25",
    database="project"
)

In [38]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [43]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="Mrun@SQL25",
    port=3306
)

print("Connected Successfully")

Connected Successfully

In [45]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Mrun%40SQL25@localhost:3306/project"
)

df.to_sql(
    "RetailStore",
    engine,
    if_exists="replace",
    index=False
)

print("Uploaded Successfully")

Uploaded Successfully

C:\Users\Mrunmayee Joshi\AppData\Local\Temp\ipykernel_6444\802475198.py:8: UserWarning: The provided table name 'RetailStore' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(